config/routes.rb
Rails.application.routes.draw do

  root to: 'musics#index'
  resources :musics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :artist, presence: true
  validates :album, presence: true, uniqueness: true
  has_attachment :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
before_action :set_music, only: [:show, :edit, :update, :destroy]
  def index
    @musics = Music.all
  end

  def show
  end

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(music_params)
    if @music.save
      redirect_to music_path(@music.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @music.update(music_params)
      redirect_to music_path(@music.id)
    else
      render :edit
    end
  end

  def destroy
    @music.destroy
    redirect_to musics_path
  end

  private

  def music_params
    params.require(:music).permit(:title, :artist, :album, :year, :photo)
  end

  def set_music
    @music = Music.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magimix</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/musics/_form.html.erb
<%= simple_form_for @music do |f| %>
  <%= f.error_notification %>

  <%= f.input :title %>
  <%= f.input :artist %>
  <%= f.input :album %>
  <%= f.input :year %>
  <%= f.input :photo, as: :attachinary %>

  <%= f.button :submit%>
<% end %>

app/views/musics/create.html.erb
<h1>Musics#create</h1>
<p>Find me in app/views/musics/create.html.erb</p>

app/views/musics/delete.html.erb
<h1>Musics#delete</h1>
<p>Find me in app/views/musics/delete.html.erb</p>

app/views/musics/edit.html.erb
<%= render "form" %>

app/views/musics/index.html.erb
<h1> Lau's favorite musics </h1>

<% @musics.each do |music| %>
  <br>
  <% if music.photo? %>
  <%= cl_image_tag music.photo.path, width: 100, height: 100, crop: :fill %>
  <% end %>
  <%= music.title %> by <%= music.artist %>
  <%= link_to 'Details', music_path(music)%>
  <%= link_to "Delete", music_path(music),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<%end%>

<br>
<%= link_to 'Add a song', new_music_path %>

app/views/musics/new.html.erb
<%= render "form" %>

app/views/musics/show.html.erb
<% if @music.photo? %>
  <%= cl_image_tag @music.photo.path, width: 200, height: 200, crop: :fill %>
<% end %>

<h2><%= @music.title %></h2>
<h3><%= @music.artist %></h3>
<p><%= @music.album %></p>
<p><%= @music.year %></p>
<%= link_to 'Edit', edit_music_path(@music)%>

<br>
<br>
<br>
<%= link_to 'Home', musics_path %>

app/views/musics/update.html.erb
<h1>Musics#update</h1>
<p>Find me in app/views/musics/update.html.erb</p>